/**
 * This file is auto-generated by grpc-helper
 */

/* eslint-disable @typescript-eslint/no-namespace */

import * as grpcs from '@midwayjs/grpc';

/* package com start */
export namespace com {
  /* package codenotfound start */
  export namespace codenotfound {
    /* package grpc start */
    export namespace grpc {
      /* package user start */
      export namespace user {
        export interface RequestParams {
          username?: string;
          age?: number;
        }
        export interface Response {
          username?: string;
          age?: number;
        }
        export interface UserService {
          getUser(data: RequestParams): Promise<Response>;
        }
        /**
         * UserService client interface
         */
        export interface UserServiceClient {
          getUser(
            options?: grpcs.IClientOptions
          ): grpcs.IClientUnaryService<RequestParams, Response>;
        }
      }
      /* package user end */
    }
    /* package grpc end */
  }
  /* package codenotfound end */
}
/* package com end */
